### ISSUE TITLE
我引入模板不显示人物

### ISSUE THREAD

**Issue by XDRSZYHRL** [zenghongtu/PPet#10]
我引入模板不显示人物
平台信息：win10
截图上传不上来

**Comment by XDRSZYHRL** [comment]
![0](https://user-images.githubusercontent.com/59906163/73242797-e47b7f80-41e0-11ea-8c5b-37e0f5d0ca33.png)

**Comment by zenghongtu** [comment]
尝试其他的model能否使用，如果没问题的话那就是这个model的问题。
如果可以的话，上传这个model，我看看是什么问题。

**Comment by XDRSZYHRL** [comment]
其他模型也不显示人物，我就上传了一个压缩包，模板全在里面，主要是live2d-widget-model-miku这个模板。麻烦你看一下，谢谢

**Comment by XDRSZYHRL** [comment]
下载链接：https://send.firefox.com/download/129cd3d5c7209310/#4NA2GB5R8vnmFlveSbC6YA，文件上传不了，你用这个下载吧。

**Comment by XDRSZYHRL** [comment]
下载链接：https://send.firefox.com/download/129cd3d5c7209310/#4NA2GB5R8vnmFlveSbC6YA
       文件上传不了，你用这个下载吧。

**Comment by antiHero3** [comment]
您好，我也有相同的问题，使用README里面的model，导入后无法显示，请问该问题有解决方法吗？

**Comment by antiHero3** [comment]
平台环境：win10、win7

**Comment by ZhangTianrong** [comment]
这里也是，主要尝试了若干 [xiazeyu](https://github.com/xiazeyu/live2d-widget-models) 的模型，导入成功但是没有渲染出来。

**Comment by zenghongtu** [comment]
> 这里也是，主要尝试了若干 [xiazeyu](https://github.com/xiazeyu/live2d-widget-models) 的模型，导入成功但是没有渲染出来。
> Edit: 貌似其似乎并没有导入成功，显示的信息仍然是导入前的模型的。

我试了一下，没有问题的。要选择`assets`目录下的`*.model.json`文件。如果还有问题，新开一个issue

**Comment by zenghongtu** [comment]
新版本已经修复，我关闭这个issue了
