### ISSUE TITLE
不适用live2

### ISSUE THREAD

**Issue by EChinLee** [zenghongtu/PPet#125]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**

#### 问题描述

**_平台信息(win/mac/linux)：_**

**Comment by EChinLee** [comment]
你好，抱歉打扰，很喜欢PPET，但是最近发现有很多新的模型是通过Live2D3.0以上版本制作的，但是目前的PPET只支持导入2.0版本制作的模型，请问这个问题怎么解决呢，抱歉打扰了
3.0的版本模型没有motion中的mtn文件，似乎在json的很多其他方面也有所改动

**Comment by zenghongtu** [comment]
新版支持 v3 版本了
