### ISSUE TITLE
觉得加入一个选项，不用按alt，直接拖看板娘就可以移动

### ISSUE THREAD

**Issue by MomentDerek** [zenghongtu/PPet#13]
### 描述
主要是按alt太麻烦了，很多时候只是觉得她挡住了某个地方，就随手将她拖走，现在要按多一个键，感觉很不利落
或者说可以设置鼠标在看板娘上按下的时间，比如我按0.7秒（可设定）后，鼠标图标变为一个方向图标，然后这样就可以拖动了
或者说更直接的，直接在看板娘旁边的按钮中加一个拖动按钮，直接拖这个按钮就可以进行拖动

**Comment by zhmushan** [comment]
我记得直接拖动这个功能在 `win10` 上是无法实现在, 设置为 `drag` 之后, 系统会代理掉上面的鼠标事件.

PS: 打个标记跟踪这个 `ISSUE`, 看看会不会有人提出解决方案.

**Comment by linonetwo** [comment]
其实可以 按0.7秒（可设定）后 ，加上 drag 啊
