### ISSUE TITLE
这个桌宠会吃cpu🤔

### ISSUE THREAD

**Issue by Moe-hacker** [zenghongtu/PPet#146]
#### 问题描述
archlinux系统，用的cutefish桌面，cpu是6核约4Ghz的直接占用了一半，内存还出现过从200M跑到一个多G的情况，源码与release均这样。
日常剩下的一半cpu也能用，就是笔记本风扇声有点吵😥
附上不知道有没有用的/opt/PPet/ppet3的strace，应该记录到cpu飙升部分了。
[ppet.log](https://github.com/zenghongtu/PPet/files/10365551/ppet.log)

**Comment by wangzc66** [comment]
打开cpu直接飙到39%，我还以为在干嘛呢，吓得直接关掉

**Comment by inory121** [comment]
因为是用electron写的，相当于开了个chrome

**Comment by thirteenbinary** [comment]
用C\#写吧
