### ISSUE TITLE
梦象里面的model无法导入

### ISSUE THREAD

**Issue by QFJABC** [zenghongtu/PPet#16]
显示无效的model配置文件，该文件为'.json'结尾，会包含version,model,textures,motions等字段

**Comment by zyx02** [comment]
我也是，显示无效的model配置文件，该文件为'.json'结尾，会包含version,model,textures,motions等字段

**Comment by yorunouta** [comment]
我也碰到该问题，原因是梦象的model.json文件缺少version字段，自行添加可以解决，version的值任意即可
附自己的更改示例，在model.json文件中添加了下面的第三行：
"posted": "Dreamer-Paul",
	"model": "model.moc",
	**"version": "umaru1.0.0",**
	"textures": [
		"textures/texture_00.png"
	],
......

**Comment by QFJABC** [comment]
谢谢帮助

**Comment by zyx02** [comment]
谢谢帮助

**Comment by QFJABC** [comment]
但是还是无法导入

**Comment by QFJABC** [comment]
{
	"posted": "Dreamer-Paul",
	"name": "33",
	"model": "model.moc",
                "version": "umaru1.0.0",
	"textures": [
		"textures/texture_00.png"
	],
	"hit_areas_custom": {
		"head_x": [0, 0],
		"head_y": [0, 0],
		"body_x": [0, 0],
		"body_y": [0, 0]
	}
}

**Comment by yorunouta** [comment]
你好，不知道你这个代码是完整的吗，如果是的话可能是因为缺少motion字段，json文件可能不完整

**Comment by zyx02** [comment]
你好，请问导入后无法显示如何解决

**Comment by yorunouta** [comment]
可以先把宽高调成推荐比例，然后再点击重新渲染，至少我出现这个显示不全问题时是这样解决的

**Comment by zyx02** [comment]
如果是全部都没有显示呢

**Comment by yorunouta** [comment]
如果你重新渲染没有结果那我也不太清楚了，sorry～

**Comment by zyx02** [comment]
Thank you all the same

**Comment by QFJABC** [comment]
早上好，我昨天发的那一段代码是完整的，两个model的代码都没有motion字段，如果可以的话能告诉我怎么改么？或者给我发一个完整的model代码看看，谢谢！

**Comment by zenghongtu** [comment]
已经修复了，安装新版本吧~
