### ISSUE TITLE
LinuxMint 19.3 Mate使用Marco-compton和Compiz作为混成器都无法使窗口透明

### ISSUE THREAD

**Issue by q779433467** [zenghongtu/PPet#18]
#### 问题描述
使用Marco-compton和Compiz作为混成器都无法使窗口透明
**_平台信息(win/mac/linux)：Linuxmint 19.3 Tricia Amd64，使用Nvidia-340闭源驱动。_**

#### 截图（可选）
![(6~4LEQY}45J{M7(Q_7P063](https://user-images.githubusercontent.com/31182725/74420044-c9b63580-4e85-11ea-9f69-59f865f36502.png)

**Comment by q779433467** [comment]
<pre><font color="#55FF55"><b>                                       atlantis</b></font><font color="#FFFFFF"><b>@</b></font><font color="#55FF55"><b>Mint</b></font>
<font color="#55FF55"><b> MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS:</b></font> Mint 19.3 tricia
<font color="#55FF55"><b> MMm----::-://////////////oymNMd+`     Kernel:</b></font> x86_64 Linux 5.0.0-32-generic
<font color="#55FF55"><b> MMd      </b></font><font color="#FFFFFF"><b>/++                </b></font><font color="#55FF55"><b>-sNMd:    Uptime:</b></font> 1h 24m
<font color="#55FF55"><b> MMNso/`  </b></font><font color="#FFFFFF"><b>dMM    `.::-. .-::.` </b></font><font color="#55FF55"><b>.hMN:   Packages:</b></font> 2496
<font color="#55FF55"><b> ddddMMh  </b></font><font color="#FFFFFF"><b>dMM   :hNMNMNhNMNMNh: </b></font><font color="#55FF55"><b>`NMm   Shell:</b></font> zsh 5.4.2
<font color="#55FF55"><b>     NMm  </b></font><font color="#FFFFFF"><b>dMM  .NMN/-+MMM+-/NMN` </b></font><font color="#55FF55"><b>dMM   Resolution:</b></font> 1920x1080
<font color="#55FF55"><b>     NMm  </b></font><font color="#FFFFFF"><b>dMM  -MMm  `MMM   dMM. </b></font><font color="#55FF55"><b>dMM   DE:</b></font> MATE 1.22.2
<font color="#55FF55"><b>     NMm  </b></font><font color="#FFFFFF"><b>dMM  -MMm  `MMM   dMM. </b></font><font color="#55FF55"><b>dMM   WM:</b></font> Compiz
<font color="#55FF55"><b>     NMm  </b></font><font color="#FFFFFF"><b>dMM  .mmd  `mmm   yMM. </b></font><font color="#55FF55"><b>dMM   WM Theme:</b></font> Mint-Y
<font color="#55FF55"><b>     NMm  </b></font><font color="#FFFFFF"><b>dMM`  ..`   ...   ydm. </b></font><font color="#55FF55"><b>dMM   GTK Theme:</b></font> &apos;Gn-OSX-HSierra-NT-1.2.1&apos; [GTK2/3]
<font color="#55FF55"><b>     hMM- </b></font><font color="#FFFFFF"><b>+MMd/-------...-:sdds  </b></font><font color="#55FF55"><b>dMM   Icon Theme:</b></font> la-capitaine-icon-theme
<font color="#55FF55"><b>     -NMm- </b></font><font color="#FFFFFF"><b>:hNMNNNmdddddddddy/`  </b></font><font color="#55FF55"><b>dMM   Font:</b></font> 微软雅黑 weight=290 10
<font color="#55FF55"><b>      -dMNs-</b></font><font color="#FFFFFF"><b>``-::::-------.``    </b></font><font color="#55FF55"><b>dMM   CPU:</b></font> Pentium Dual-Core E6700 @ 2x 3.193GHz [34.0°C]
<font color="#55FF55"><b>       `/dMNmy+/:-------------:/yMMM   GPU:</b></font> GeForce 9800 GT
<font color="#55FF55"><b>          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM:</b></font> 3175MiB / 5957MiB
<font color="#55FF55"><b>             \.MMMMMMMMMMMMMMMMMMM    </b></font>
<font color="#55FF55"><b>                                      </b></font>
</pre>``

**Comment by q779433467** [comment]
。。。。。。
清除设置就好了。。。。。

**Comment by zenghongtu** [comment]
。。。。。。
