### ISSUE TITLE
直接显示不出来

### ISSUE THREAD

**Issue by dafeiyangxyy** [zenghongtu/PPet#19]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**
是
#### 问题描述
无法显示
**_平台信息(win/mac/linux)：_**
win
#### 截图（可选）
![~95@1ARZ`(S_3E5AS5(IBUM](https://user-images.githubusercontent.com/61033831/74490993-548a4500-4f05-11ea-889a-d54ca7a6b0a9.png)

**Comment by zenghongtu** [comment]
昨天服务器问题，已经修复了
