### ISSUE TITLE
显示不了人物

### ISSUE THREAD

**Issue by Luclifer** [zenghongtu/PPet#20]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**
是
#### 问题描述
安装完以后，显示不了人物，好悲哀~~~~
**_平台信息(win/mac/linux)：_**
win10(DEll)

**Comment by XDRSZYHRL** [comment]
我也是不显示人物，重新渲染也没用，平台为win10

**Comment by ESCwuyan** [comment]
我也是，win10 1809 版本号17763.1039

**Comment by 652436962** [comment]
我是1903，也有这个问题

**Comment by zenghongtu** [comment]
@Luclifer @ESCwuyan @XDRSZYHRL @652436962 

服务器问题，再打开试试。如果有问题再开 issue
