### ISSUE TITLE
本地 model 导入后无法显示

### ISSUE THREAD

**Issue by QFJABC** [zenghongtu/PPet#22]
问题描述
梦象里面的model导入后无法显示，一片空白，只能显示工具
平台信息(win/mac/linux)：Windows 10 1909

**Comment by zenghongtu** [comment]
哪个model? 给个链接我看看

**Comment by QFJABC** [comment]
https://mx.paul.ren/model/umaru.html
https://mx.paul.ren/model/yuri.html

**Comment by QFJABC** [comment]
许多model都失败

**Comment by zenghongtu** [comment]
我试了一下这两个都没有问题的哈

![image](https://user-images.githubusercontent.com/25629121/74628413-a397da80-5190-11ea-84a1-5d3d1bdd7b66.png)

onedrive 直接点击左上角的'下载按钮'下载,把整个文件夹下载下来，再选择文件夹中的model.json导入模型

![image](https://user-images.githubusercontent.com/25629121/74628578-fa9daf80-5190-11ea-9bbb-ca71c10b310b.png)

**Comment by QFJABC** [comment]
![捕获](https://user-images.githubusercontent.com/49907719/74699275-355c2200-523b-11ea-8e58-399ff78f4e61.PNG)

**Comment by QFJABC** [comment]
刚试了，还不行

**Comment by QFJABC** [comment]
重新渲染，调整大小都试过了

**Comment by QFJABC** [comment]
![捕获](https://user-images.githubusercontent.com/49907719/74699509-d0ed9280-523b-11ea-9784-08a8fe317b66.PNG)

**Comment by modernbaby** [comment]
我也是同样的问题哦，下载下来的模特都显示不出。

**Comment by TaciturnBoy** [comment]
同样的情况，不知道哪里出了问题。。。。

**Comment by TaciturnBoy** [comment]
![TIM截图20200302193630](https://user-images.githubusercontent.com/50647700/75673453-ed6adf80-5cbd-11ea-84b8-7d84e1627619.jpg)

**Comment by Weilet** [comment]
The same promble. It didn't work even if I rewrote modle.json. Here is the modle's [address](https://mx.paul.ren/model/kanna.html)
![image](https://user-images.githubusercontent.com/32561597/75763132-bad0ed80-5d76-11ea-914f-6c262335dc92.png)

**Comment by gwq20521** [comment]
老板，我的也不行啊……
视图内一片空白，点击移动倒是还可以移动，只不过是一片透明空白。少了换人和换装按钮。
这里面也没法传输图片展示。 [https://w.url.cn/s/AIBxVmr](url) 给个地址，你看看现象。截图工具能自动识别画布模块，但是是全透明的。背景是我自己的桌面。
这个不会跟主题设置有关系吧？没有完成置顶？但是程序自带的模型就可以正常显示和换人、换装。
除了有时候，可能模型比较大，加载的时候，会出现短暂的全透明以外，都能正常使用。
是还需要进行别的操作吗？需要自己切换吗？

另外问下~
下载文件里的 PPet-1.1.0.dmg PPet-1.1.0.deb PPet-1.1.0.zip在安装完毕之后还有用吗？

**Comment by lightloveEnV** [comment]
这个应该是系统bug，win的有问题，mac的就没问题

**Comment by lightloveEnV** [comment]
希望解决一下win这边的问题

**Comment by zenghongtu** [comment]
@lightloveEnV @gwq20521 @Weilet @TaciturnBoy @modernbaby @QFJABC 
已修复，安装v1.2.1即可~

**Comment by gwq20521** [comment]
好用。赞。膜拜大神~
