### ISSUE TITLE
建议大佬开发一个类似miku的插件

### ISSUE THREAD

**Issue by binglumeng** [zenghongtu/PPet#29]
### 描述
https://github.com/sunqibuhuake/atom-miku
大佬可以参照初音未来这个项目，移植一下，做个全平台的桌宠么？

**Comment by 1728551979** [comment]
555，我愧为计算机系学生。。。作者大大可以发个能移动位置的功能么，只能呆右下角容易跟输入法重一起。

**Comment by binglumeng** [comment]
> 555，我愧为计算机系学生。。。作者大大可以发个能移动位置的功能么，只能呆右下角容易跟输入法重一起。
似乎是可以拖动的啊，Mac下是`option`键，然后鼠标拖动。对应`Windows`是不是`Alt`加鼠标拖动，试试？

**Comment by 1728551979** [comment]
作者大大还是不会忘记这种小细节啊/doge，我多虑了，不过没说明第一次用的话不会知道的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"冰路梦"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 晚上10:22
收件人:&nbsp;"zenghongtu/PPet"<PPet@noreply.github.com&gt;;
抄送:&nbsp;"清羽"<1728551979@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zenghongtu/PPet] 建议大佬开发一个类似miku的插件 (#29)





  
555，我愧为计算机系学生。。。作者大大可以发个能移动位置的功能么，只能呆右下角容易跟输入法重一起。
 似乎是可以拖动的啊，Mac下是option键，然后鼠标拖动。对应Windows是不是Alt加鼠标拖动，试试？

**Comment by zenghongtu** [comment]
底层技术不一样，移植太高难度了~~

另外：如果是要miku，可以直接导入这个地址 （v1.2版本)

https://raw.githubusercontent.com/xiazeyu/live2d-widget-models/master/packages/live2d-widget-model-miku/assets/miku.model.json

效果还阔以👇

![image](https://user-images.githubusercontent.com/25629121/76761513-83c4f800-67ca-11ea-9e96-6016d2ba72ef.png)

**Comment by binglumeng** [comment]
多谢大佬，不太熟悉这类技术，还是表示感谢！
