### ISSUE TITLE
无法安装1.2

### ISSUE THREAD

**Issue by catnines** [zenghongtu/PPet#35]
问题描述：
1.2的安装程序安装到还没一半就会显示“安装已中止，安装程序并未成功地运行完成”

前因：
1.在更新前我在用1.1；然后第一次安装1.2时成功了，体验插件功能时不小心删除了第四个插件（你的插件真的很容易就被点到删除，建议加一个删除确认）。然后我再次安装1.2，丢失的数据并没有修复。
2.于是我删除了整个安装文件夹，然后就无法安装。
3.之后我尝试了换版本，换安装目录，关闭防火墙和杀毒软件，重启电脑……全部以失败告终。回收站的文件也没了（因为我每天都要删很多东西）

希望你能帮忙解决我的问题！

**Comment by zenghongtu** [comment]
@catnines Hi~ 安装中止是因为上一次安装没有正常卸载。可以桌面左下角右键点击“程序和功能”，找到PPet，右键点击“卸载”。然后再安装就好了。
如果删除的是默认插件，可以点刷新试试，会有网络延迟。或者关闭窗口再开就有了

**Comment by catnines** [comment]
谢谢！已解决
