### ISSUE TITLE
Unable to import live2d model

### ISSUE THREAD

**Issue by NightmareDreemurr** [zenghongtu/PPet#36]
我之前在梦象下了几个模型，然后按照所讲的设置导入了，导入了之后我的看板娘就变成透明的了= =
![84J3V84~TW~`17EBBTUQCMU](https://user-images.githubusercontent.com/59122229/76811920-3c705300-682e-11ea-86df-ac8645e258f9.png)
![$7V {}`QVNL0K29GJHXX_HG](https://user-images.githubusercontent.com/59122229/76811943-4abe6f00-682e-11ea-84d5-62f779b13adc.png)

**Comment by lightloveEnV** [comment]
我的也一样，用本地和在线的都是空白。。。好像说win版的有问题，mac和linux的就没问题
![image](https://user-images.githubusercontent.com/62276155/76825730-a8b27d00-6855-11ea-8066-12aed65c9270.png)

**Comment by NightmareDreemurr** [comment]
好的 谢谢解答
希望以后能够修复吧 加油
