### ISSUE TITLE
建议勾选“忽略点击”以后，人物仍可以追踪鼠标。

### ISSUE THREAD

**Issue by Acris** [zenghongtu/PPet#4]
现在勾选“忽略点击”以后，人物直接就傻掉了，建议勾选“忽略点击”以后，人物仍可以追踪鼠标，眼睛可以跟随鼠标指针移动，人物也能随机说话，“忽略点击”仅仅做点击穿透。

**Comment by ShikieikiC** [comment]
+1+1+1
