### ISSUE TITLE
有些模型只能看到半身

### ISSUE THREAD

**Issue by lightloveEnV** [zenghongtu/PPet#42]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**

#### 问题描述：有些模型只能看到半身

**_平台信息(win/mac/linux)：win8.1_**

#### 截图（可选）
![捕获](https://user-images.githubusercontent.com/62276155/77150059-f33e2e80-6acd-11ea-8fba-12011f67d0e2.PNG)

**Comment by zenghongtu** [comment]
菜单栏-> 设置，调节画布大小，把高度大一点就有了
