### ISSUE TITLE
大大你的看板娘又挂啦！

### ISSUE THREAD

**Issue by kawashiro-ryofu** [zenghongtu/PPet#63]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**
昨天刚刚从Github上下载
#### 问题描述
安装完显卡驱动后重启，就挂了，不显示
之前我用Manjaro的时候没问题的啊……
**_平台信息(win/mac/linux)：_**
Xubuntu 20.04
#### 截图（可选）
![截图_2020-07-06_18-14-18](https://user-images.githubusercontent.com/53611149/86582829-dc581500-bfb4-11ea-9f38-df535ce16507.png)

**Comment by kawashiro-ryofu** [comment]
重新安装没有作用

**Comment by kawashiro-ryofu** [comment]
![截图_2020-07-06_18-30-29](https://user-images.githubusercontent.com/53611149/86583980-c6e3ea80-bfb6-11ea-946c-39e20327ac5a.png)
这可能是错误产生原因，但我不会Node和Electron，所以……

**Comment by kawashiro-ryofu** [comment]
![截图_2020-07-06_18-30-29](https://user-images.githubusercontent.com/53611149/86584075-f1ce3e80-bfb6-11ea-9978-93adadebdb0d.png)
 这可能是错误产生原因，但我不会Node和Electron，所以……

**Comment by kawashiro-ryofu** [comment]
这可能是错误产生原因，但我不会Node和Electron，所以……
![截图_2020-07-06_18-30-29](https://user-images.githubusercontent.com/53611149/86584101-fdba0080-bfb6-11ea-8faa-82a8c9184659.png)

**Comment by caoxuenian** [comment]
linuxmint20中也是这样子

**Comment by ToaruOsaka** [comment]
额, ubuntu 20.04, 直接下大佬的 deb, 起来后, 也是这样子....

**Comment by zenghongtu** [comment]
服务器ssl证书挂了，导致域名打不开。现在修复了。
