### ISSUE TITLE
Manjaro有没有

### ISSUE THREAD

**Issue by tangsu99** [zenghongtu/PPet#74]
Manjaro能不能用有没有

**Comment by ashremdream** [comment]
> Manjaro能不能用有没有

yay -S ppet-bin,我是Arch用户

**Comment by tangsu99** [comment]
> > Manjaro能不能用有没有
> 
> yay -S ppet-bin,我是Arch用户

会报错，我没找到解决方法，比较小白
 ==> 错误： Cannot find the strip binary required for object file stripping.
 下载源文件时出错: ppet-bin
用这个方法成功安装了 https://zhuanlan.zhihu.com/p/100959322
谢谢大佬
@ashremdream

**Comment by bigshans** [comment]
arch 打包， https://github.com/bigshans/PPet-bin-PKGBUILD ， Manjaro 应该适用。
