### ISSUE TITLE
manjaro无法正常显示

### ISSUE THREAD

**Issue by ghost** [zenghongtu/PPet#75]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**
名字           : ppet
版本           : 1.2.1-1
描述           : 给你的桌面添加一点趣味~
架构           : x86_64
URL            : https://github.com/zenghongtu/PPet
#### 问题描述
人物无模型
**_平台信息(win/mac/linux)：_**
Linux  5.8.11-1-MANJARO
#### 截图（可选）
![image](https://user-images.githubusercontent.com/71248920/94908116-d0a4bd80-04d3-11eb-9b27-05e836614541.png)

**Comment by tangsu99** [comment]
你是怎么安装的,我的可以正常显示,应该是和你一样的  Manjaro 20.1.1 x86_64 Linux 5.8.11-1-MANJARO    ppet-1.2.1-1

**Comment by ghost** [comment]
之前是用yay -S ppet-bin安装的，安装过程没问题。刚刚用了你提供的方法安装后，启动还是和截图一样，没有模型。难道是我电脑的锅？。。

**Comment by tangsu99** [comment]
好像加载有点慢，你试试点切换人物，点快点，多点几下， 再等一会，看看能加载出来吗

**Comment by tangsu99** [comment]
截图我这加载不出来

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/71248920/94995163-0da1aa80-05cf-11eb-9787-b98bc6860c23.png)

**Comment by ChrysosKun** [comment]
![Uploading image.png…]()

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/71248920/94995206-62452580-05cf-11eb-9fba-5c5143906053.png)

**Comment by ghost** [comment]
this fails for some browsers.....我用的chromium

**Comment by ghost** [comment]
多点几下没用，应该是上面这个问题

**Comment by ghost** [comment]
根据提示点了链接，浏览器支持WebGL
![image](https://user-images.githubusercontent.com/71248920/94995380-86553680-05d0-11eb-86ad-bf0c6c395d58.png)

**Comment by tangsu99** [comment]
我也无能为力了，你去反馈一下

**Comment by tangsu99** [comment]
解决了没有

**Comment by ghost** [comment]
还是不行

**Comment by tangsu99** [comment]
反馈一下吧，我也不懂程序

**Comment by ghost** [comment]
嗯嗯，好

**Comment by LeeBunker** [comment]
可以试试加入 --no-sandbox 启动选项

**Comment by ghost** [comment]
感谢，已解决
