### ISSUE TITLE
WebGL和人物模型无法显示问题

### ISSUE THREAD

**Issue by ghost** [zenghongtu/PPet#77]
**请先确认是否为[最新版本](https://github.com/zenghongtu/PPet/releases/latest)**
名字 : ppet
版本 : 1.2.1-1
描述 : 给你的桌面添加一点趣味~
架构 : x86_64
URL : https://github.com/zenghongtu/PPet
#### 问题描述
浏览器支持WebGL,控制台错误提示为“浏览器不支持WebGL"。
人物模型无法显示。
猜测是因为WebGL问题导致人物模型无法显示
**_平台信息(win/mac/linux)：_**
Linux 5.8.11-1-MANJARO
#### 截图（可选）
浏览器支持WebGL
![image](https://user-images.githubusercontent.com/71248920/94996070-f5348e80-05d4-11eb-8fd0-dfc123f735e7.png)

调试错误提示
![image](https://user-images.githubusercontent.com/71248920/94996098-172e1100-05d5-11eb-8533-a25595130038.png)

人物模型
![image](https://user-images.githubusercontent.com/71248920/94996130-493f7300-05d5-11eb-88e2-f93c65068b59.png)

**Comment by LeeBunker** [comment]
加入 --no-sandbox 启动选项

**Comment by ghost** [comment]
感谢，已解决
